# Generated by Django 4.0.6 on 2022-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyurl', models.TextField()),
                ('pharmacyname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('sources', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='commms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyurl', models.TextField()),
                ('pharmacyname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('sources', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
