# Generated by Django 4.0.6 on 2022-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyurl', models.TextField()),
                ('pharmacyname', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('sources', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='commms',
        ),
    ]
